In [117]:
import seaborn as sns
import sklearn
import numpy as np
data = sns.load_dataset('tips')

X = np.array(data['total_bill'].astype(np.int64)).reshape(-1,1)
y = np.array(data['tip'].astype(np.int64)).reshape(-1,1)

In [118]:
print(X.shape)

(244, 1)


In [119]:
print(y.shape)

(244, 1)


In [120]:
print(X)

[[16]
 [10]
 [21]
 [23]
 [24]
 [25]
 [ 8]
 [26]
 [15]
 [14]
 [10]
 [35]
 [15]
 [18]
 [14]
 [21]
 [10]
 [16]
 [16]
 [20]
 [17]
 [20]
 [15]
 [39]
 [19]
 [17]
 [13]
 [12]
 [21]
 [19]
 [ 9]
 [18]
 [15]
 [20]
 [17]
 [24]
 [16]
 [16]
 [18]
 [31]
 [16]
 [17]
 [13]
 [ 9]
 [30]
 [18]
 [22]
 [32]
 [28]
 [18]
 [12]
 [10]
 [34]
 [ 9]
 [25]
 [19]
 [38]
 [26]
 [11]
 [48]
 [20]
 [13]
 [11]
 [18]
 [17]
 [20]
 [16]
 [ 3]
 [20]
 [15]
 [12]
 [17]
 [26]
 [25]
 [14]
 [10]
 [17]
 [27]
 [22]
 [17]
 [19]
 [16]
 [10]
 [32]
 [15]
 [34]
 [13]
 [18]
 [24]
 [21]
 [28]
 [22]
 [ 5]
 [16]
 [22]
 [40]
 [27]
 [12]
 [21]
 [12]
 [11]
 [15]
 [44]
 [22]
 [20]
 [15]
 [20]
 [25]
 [18]
 [14]
 [14]
 [ 7]
 [38]
 [23]
 [25]
 [17]
 [29]
 [10]
 [12]
 [24]
 [11]
 [13]
 [14]
 [15]
 [12]
 [29]
 [ 8]
 [14]
 [11]
 [22]
 [19]
 [20]
 [11]
 [12]
 [18]
 [ 8]
 [10]
 [14]
 [16]
 [13]
 [17]
 [34]
 [41]
 [27]
 [16]
 [ 8]
 [18]
 [11]
 [ 9]
 [ 7]
 [14]
 [13]
 [17]
 [24]
 [19]
 [29]
 [48]
 [25]
 [13]
 [16]
 [21]
 [12]
 [16]
 [13]
 [17]
 [24]
 [20

In [121]:
print(y)

[[ 1]
 [ 1]
 [ 3]
 [ 3]
 [ 3]
 [ 4]
 [ 2]
 [ 3]
 [ 1]
 [ 3]
 [ 1]
 [ 5]
 [ 1]
 [ 3]
 [ 3]
 [ 3]
 [ 1]
 [ 3]
 [ 3]
 [ 3]
 [ 4]
 [ 2]
 [ 2]
 [ 7]
 [ 3]
 [ 2]
 [ 2]
 [ 2]
 [ 4]
 [ 3]
 [ 1]
 [ 2]
 [ 3]
 [ 2]
 [ 3]
 [ 3]
 [ 2]
 [ 3]
 [ 2]
 [ 5]
 [ 2]
 [ 2]
 [ 3]
 [ 1]
 [ 5]
 [ 3]
 [ 5]
 [ 6]
 [ 2]
 [ 3]
 [ 2]
 [ 2]
 [ 5]
 [ 1]
 [ 4]
 [ 3]
 [ 3]
 [ 1]
 [ 1]
 [ 6]
 [ 3]
 [ 2]
 [ 1]
 [ 3]
 [ 2]
 [ 3]
 [ 2]
 [ 1]
 [ 2]
 [ 2]
 [ 1]
 [ 3]
 [ 3]
 [ 5]
 [ 2]
 [ 1]
 [ 3]
 [ 4]
 [ 3]
 [ 2]
 [ 3]
 [ 3]
 [ 1]
 [ 5]
 [ 2]
 [ 5]
 [ 2]
 [ 4]
 [ 5]
 [ 3]
 [ 3]
 [ 3]
 [ 1]
 [ 4]
 [ 3]
 [ 4]
 [ 4]
 [ 1]
 [ 3]
 [ 1]
 [ 2]
 [ 3]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 4]
 [ 3]
 [ 4]
 [ 3]
 [ 1]
 [ 4]
 [ 2]
 [ 4]
 [ 3]
 [ 5]
 [ 1]
 [ 1]
 [ 2]
 [ 2]
 [ 1]
 [ 2]
 [ 2]
 [ 2]
 [ 4]
 [ 1]
 [ 2]
 [ 2]
 [ 2]
 [ 1]
 [ 2]
 [ 1]
 [ 2]
 [ 3]
 [ 1]
 [ 2]
 [ 2]
 [ 2]
 [ 2]
 [ 3]
 [ 6]
 [ 5]
 [ 5]
 [ 2]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [ 2]
 [ 2]
 [ 2]
 [ 2]
 [ 2]
 [ 2]
 [ 5]
 [ 5]
 [ 3]
 [ 2]
 [ 2]
 [ 3]
 [ 2]
 [ 2]
 [ 2]
 [ 3]
 [ 3]
 [ 2

In [122]:
# Дополните код для работы программы на месте троеточия "..."

# Импортируйте функцию train_test_split и логистическую регрессию
# А также MSE
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error

# Разделите данные на тренировочную и тестовые выборки, с отношением 20%

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42,test_size= .2)

# Инициализируйте и обучите модель на тренировочной выборке 
model = LogisticRegression(random_state=42)
model.fit(X_train,y_train)

# Сделайте предсказание на тестовой выборке
pred = model.predict(X_test)
print(pred)

[2 1 3 3 2 2 3 2 2 2 2 1 1 2 1 2 2 3 2 3 3 3 2 1 3 1 1 3 2 5 3 1 2 3 2 3 2
 5 2 3 1 2 3 1 1 1 1 2 1]


C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [123]:
# Выведите среднеквадратичную ошибку предсказания
mse = mean_squared_error(pred, y_test)
print(mse)

0.7551020408163265


In [124]:
# Импортируйте кросс-валидацию
from sklearn.model_selection import KFold
# Инициализируйте кросс-валидацию с 5ю фолдами
from sklearn.metrics import mean_absolute_error

def cross_validation(model, X, y, random_state = 10):
    scores = []
    kf = KFold(5)
    iter_num = 1
    for train_index, test_index in kf.split(X):
        print(f'Iteration {iter_num}:')

        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
         
    model.fit(X_train, y_train)

        pred = model.predict(X_test)

        print(f'MAE fold {iter_num}:', mean_absolute_error(pred, y_test))

        iter_num += 1
        
        scores.append(mean_absolute_error(pred, y_test))
    print("Mean overall:", sum(scores) / len(scores))
    return


IndentationError: unexpected indent (<ipython-input-124-846c26d195f6>, line 18)

In [125]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()


cross_validation(lin_reg, X, y)

NameError: name 'cross_validation' is not defined

In [126]:
# Выведите результаты кросс-валидации и среднее
from sklearn.model_selection import cross_validate

cv = cross_validate(lin_reg, X, y, cv = 5)

print(cv['test_score'])

print("Среднее отколнение:", cv['test_score'].mean())

[0.54478546 0.62020894 0.43913981 0.22374743 0.44441692]
Среднее отколнение: 0.45445971446095756
